name: Dev workflow
run-name: ${{ github.actor }} is running pipeline
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - dev
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: actions/checkout@v3
        run: yarn test
